//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDP_02.Models
{
    using System;
    
    public partial class GetBaoCaoTonKho_Result1
    {
        public Nullable<long> stt { get; set; }
        public string TenSanPham { get; set; }
        public string TenTinhChatDongPhuc { get; set; }
        public string TenLoaiSanPham { get; set; }
        public string MaSize { get; set; }
        public string TenDonViTinh { get; set; }
        public int tonDauKi { get; set; }
        public int nhaptrongki { get; set; }
        public int xuatrongki { get; set; }
        public Nullable<int> toncuoi { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
    }
}
